version: "3.9"
services:
  nats:
    image: nats:2.10-alpine
    command: ["-js"]
    ports: ["4222:4222", "8222:8222"]
    restart: unless-stopped
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: trader
      POSTGRES_DB: trader
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    restart: unless-stopped
volumes:
  pgdata:
