# config/config.example.yaml
# Copy to config.yaml and adjust as needed.

trading_mode: paper          # paper | live | dry-run
global_pause: true           # kill switch for all new orders

thresholds:
  positive: 0.35
  very_positive: 0.65

risk:
  per_symbol_cap_nav_pct: 5
  per_order_max_usd: 25000
  daily_new_exposure_cap_nav_pct: 15
  stop_loss_pct: 6
  daily_drawdown_pause_nav_pct: 3
  cooldown_minutes: 5

risk_controls:
  stop_loss:
    enabled: true
    default_stop_loss_pct: 6
    emergency_stop_loss_pct: 10
    allow_after_hours: false
    cooldown_hours: 24

  sector_limits:
    enabled: true
    max_sector_exposure_pct: 40
    sector_map:
      AAPL: tech
      MSFT: tech
      GOOGL: tech
      NVDA: tech
      JPM: finance
      BAC: finance
      GS: finance
      BIOX: biotech
      GILD: biotech
      MRNA: biotech

  drawdown:
    enabled: true
    daily_warning_pct: 2.0
    daily_pause_pct: 3.0
    weekly_warning_pct: 5.0
    weekly_pause_pct: 8.0
    size_multiplier_on_warning_pct: 50

monitoring:
  dashboard_recent_trades: 5
  health_check_interval_minutes: 5

corroboration:
  require_positive_pr: true
  window_seconds: 900        # 15 minutes

earnings:
  enabled: true
  block_on_estimated: false   # if true, treat estimated like confirmed
  minutes_before: 30          # optional pre-window
  minutes_after: 30           # optional post-window

liquidity:
  target_realized_vol_5m: 0.015
  max_spread_bps: 30

session:
  block_first_minutes: 5
  block_last_minutes: 5
  allow_after_hours: false
  block_premarket: true
  block_postmarket: true


paper:
  outbox_path: "data/outbox.jsonl"
  latency_ms_min: 100
  latency_ms_max: 2000
  slippage_bps_min: 1
  slippage_bps_max: 5
  dedupe_window_seconds: 90

wire:
  enabled: false
  base_url: "http://127.0.0.1:8091"
  transport: "sse"                  # "sse" or "http"
  timeout_seconds: 30
  max_events: -1                    # -1 = unlimited, for bounded test runs
  max_duration_seconds: -1          # -1 = unlimited, for bounded test runs
  reconnect:
    initial_delay_ms: 1000
    max_delay_ms: 16000
    max_attempts: -1                # -1 = infinite
    jitter_ms: 250
  heartbeat_seconds: 10
  max_channel_buffer: 10000
  fallback_to_http_after_failures: 5
  # Legacy HTTP polling settings (backward compatibility)
  poll_interval_ms: 1000
  timeout_ms: 5000
  max_retries: 3
  backoff_base_ms: 100
  backoff_max_ms: 5000

adapters:
  NEWS_FEED: stub            # later: benzinga|reuters|custom
  QUOTES: sim                # later: polygon|broker
  HALTS: sim                 # later: nasdaq|nyse
  SENTIMENT: stub            # later: finbert|vendor
  BROKER: paper              # later: alpaca|ibkr
  ALERTS: stdout             # later: slack|email

slack:
  enabled: false
  webhook_url: "http://127.0.0.1:8093/webhook"  # mock for testing
  channel_default: "#trading-alerts"
  alert_on_buy_1x: false
  alert_on_buy_5x: true
  alert_on_reject_gates: true
  rate_limit_per_min: 10
  rate_limit_per_symbol_per_min: 3

runtime_overrides:
  enabled: true
  file_path: "data/runtime_overrides.json"
  refresh_interval_ms: 10000
  expiry_hours_default: 24

security:
  slack_signing_secret_env: "SLACK_SIGNING_SECRET"
  allowed_slack_user_ids: []  # empty = no RBAC

portfolio:
  enabled: true
  state_file_path: "data/portfolio_state.json"
  max_position_size_usd: 25000           # per-symbol position limit
  max_portfolio_exposure_pct: 15         # total exposure as % of capital
  daily_trade_limit_per_symbol: 5        # max trades per symbol per day
  cooldown_minutes_per_symbol: 5         # minimum time between trades
  max_daily_exposure_increase_pct: 10    # daily new exposure limit
  reset_daily_limits_at_hour: 9          # UTC hour to reset daily counters
  position_decay_days: 30                # days to keep position history

# alert sinks (example)
alerts:
  slack_webhook_url: ""      # set in secrets manager or env
  email_recipients: []       # e.g., ["ops@example.com"]
